### ISSUE TITLE
Imports, JS/TS support, Lua definitions

### ISSUE THREAD

**Issue by thelindat** [overextended/ox_core#10]
Lua types: https://github.com/overextended/ox_types
TS types: https://www.npmjs.com/package/@overextended/ox_core

---

Since player and vehicle classes are built around metatables and an export to handle method access, more glue code is required to build for ox_core than you would use for ESX or QB (no closures for easy function refs).

JS and TS support comes secondary to Lua and won't be worked on much until ox_core is closer to a stable state - rewriting to support multiple languages is a bit of a hassle.

C# support is not even a consideration at this point.

---

I wrote some incomplete JS imports to match the CPlayer behaviour in Lua, but we will ideally publish a node_module _instead_.

For Lua, some work will need to be done to the settings shared for [sumneko-lua](https://marketplace.visualstudio.com/items?itemName=sumneko.lua) and [cfxlua](https://github.com/overextended/cfxlua-vscode) support. A separate library with stub functions should be written, rather than relying on in-line LuaDocs that require the entire resource to be loaded into the workspace.

**Comment by Cyntaax** [comment]
> ... A separate library with stub functions should be written, rather than relying on in-line LuaDocs that require the entire 
> resource to be loaded into the workspace.

What do you mean by this exactly? I was going to at some point recommend/do documentation using [EmmyLua](https://emmylua.github.io/) doc. It seems to work well with the vscode sumneko-lua plugin and is the go-to plugin for Jetbrains users (like myself)

**Comment by thelindat** [comment]
TypeScript library and types are implemented at https://www.npmjs.com/package/@overextended/ox_core

**Comment by thelindat** [comment]
Lua types are available at https://github.com/overextended/ox_types
