### ISSUE TITLE
Error selecting the character

### ISSUE THREAD

**Issue by CoachYT1** [overextended/ox_core#108]
I'm using the latest commit. When i select the character this error appears
![image](https://github.com/overextended/ox_core/assets/69034647/a258123e-72f4-40dd-913d-26e138ea233e)

**Comment by thelindat** [comment]
Should have been resolved with https://github.com/overextended/ox_core/commit/f25cf30bc3676fdadc43d175f086a64c2c323339.
For whatever reason my JSON was never auto-parsing, but it was some - and seemingly you, even with this change?

May need to look at typecasting.

**Comment by CoachYT1** [comment]
I'm sorry for wasting your time... I pulled the git repo without building the update. The issue Is fixed.
