### ISSUE TITLE
External multicharacter support

### ISSUE THREAD

**Issue by thelindat** [overextended/ox_core#112]
Spawn system needs to be exported and made usable from other resources. Other resources should _only_ need to implement some basic logic and events to trigger the internal spawn system, while implementing their own spawn select, character select, character creation, etc.

Will probably port the old spawn/character system from Lua ox_core to another resource - making it easier to modify and, more importantly, optional. Keeping dependencies low is important.

**Comment by Br0kenMaverick** [comment]
Hope that "probably" becomes a "definetly" once the rebuild is done! The old spawn and character ui was extremely clean!

**Comment by MauroNr1** [comment]
> Hope that "probably" becomes a "definetly" once the rebuild is done! The old spawn and character ui was extremely clean!

Yea it was really nice
