### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by thelindat** [overextended/ox_core#119]
Compiled list of known breaking changes.
Written with a focus on Lua syntax, but should be mostly consistent across languages.

# Breaking changes from v0.19.0
## Common
- Lua imports path changed to `@ox_core.lib.init`
- `player.hasGroup` filtering moved into `player.getGroup`
- `adminGrade` is no longer used by groups

## Server
- `Ox.CreateVehicle` is now for creating new vehicles _only_ - use `Ox.SpawnVehicle` to spawn using a dbId
- `Ox.GetPlayerByFilter` renamed to `Ox.GetPlayerFromFilter`

## Client
- `player` replaced with `Ox.GetPlayer()`
- `Ox.GetPlayer()` will always return an object - checks for active player can use `player.charId`
- indexing `player` no longer calls `player.get` and must be explicit - i.e. `player.get('gender')`
- `player.groups` is no longer valid, use `player.getGroups()` or `player.getGroup(name)`

## SQL
- `character_licenses.issued` has been replaced with `character_licenses.data` (see install.sql)

**Comment by thelindat** [comment]
> CreateVehicle now use a array instead of vec3 for coords

It should accept an array, map, or vector.

**Comment by CeebDev** [comment]
> It should accept an array, map, or vector.

Then it's a problem, when i log coord it return a buffer and vehicle spawn at 0, 0, 0

**Comment by CeebDev** [comment]
https://forum.cfx.re/t/lua-vectors-dont-serialize-to-arrays-through-events/4772780/2

**Comment by CeebDev** [comment]
`Ox.GetPlayerByFilter` is replaced by `Ox.GetPlayerFromFilter`
