### ISSUE TITLE
Ox inventory update 

### ISSUE THREAD

**Issue by jahlil95** [overextended/ox_core#156]
Ive re installed the source multiple times. Not sure whats giving this error.

> ensure ox_inventory
[           resources] Stopping resource ox_inventory
[    c-scripting-core] Creating script environments for ox_inventory
[       script:ox_lib] ox_inventory requires version '0.21.3' of 'ox_core' (current version: unknown)
[           resources] Started resource ox_inventory

**Comment by thelindat** [comment]
Sounds to me like you don't have ox_core.
