### ISSUE TITLE
Amount is not a number on Ox.RemoveAccountBalance

### ISSUE THREAD

**Issue by Skryptific** [overextended/ox_core#161]
When using the RemoveAccountBalance method, I get the following error message:

![image](https://github.com/user-attachments/assets/74213f88-70d1-40e8-ab00-c242b51a111d)

Code I am using:
```lua
local fee = Fees[class]
local player = Ox.GetPlayer(vehicle.owner)
local account = player.getAccount()

lib.print.info(type(fee), fee, account.balance)

if not Ox.RemoveAccountBalance(account.id, fee, false, locale('vehicle_impound', vehicle.plate)) then
...
end
```

Pretty sure this is a number though.

**Comment by googleoblivion** [comment]
How is Fees defined?

**Comment by thelindat** [comment]
The account exports take objects rather than individual params as of a while ago now.

https://github.com/overextended/ox_core/blob/af5675ce8fa873694f5c4af1b2ca68066a7e326d/server/accounts/index.ts#L68-L70
