### ISSUE TITLE
Clarification on ox_core Performance Spikes Observed in Profiler

### ISSUE THREAD

**Issue by Primordial-Devv** [overextended/ox_core#173]
Hi there,

First off, thank you for the amazing work you’ve done with ox_core. It’s a great tool for development, and I truly appreciate the effort that has gone into this project.

I am a developer currently testing and experimenting with ox_core on my development server. I recently started monitoring its performance using the built-in FiveM profiler. While the overall performance is generally excellent, I noticed some behavior that left me with a few questions, and I’d like to ask for your insights.

Specifically, I’ve observed the following in the profiler:

___________________________________________________________________________________________________________________________

- ox_core typically runs at around 0.00ms to 0.01ms, which seems perfect.
- However, on certain ticks, I notice performance spikes where ox_core jumps to 0.10ms or 0.20ms momentarily.
- Due to these spikes, I’ve noticed that on average, the framework runs at 0.10ms.
___________________________________________________________________________________________________________________________

This pattern isn’t constant but occurs periodically. While this isn’t currently causing major issues on my development server, I was curious if these occasional spikes are expected behavior due to the nature of ox_core, or if they might indicate something worth investigating further.

___________________________________________________________________________________________________________________________

## Key Observations
- **Baseline Performance:** 0.00ms - 0.01ms (most of the time)
- **Spikes:** Occasionally up to 0.10ms - 0.20ms during certain ticks.
- **Average Performance:** Around 0.10ms due to the occasional spikes.

___________________________________________________________________________________________________________________________

## My Questions
1. Is this variability normal for a framework like ox_core, or could there be an underlying process that causes these spikes at specific intervals?

2. Should I be concerned about these occasional increases in processing time, especially in a development environment where I aim to maintain high-performance standards?

3. Are there any known strategies or optimizations to reduce these kinds of performance variations?

I’m aware that some variability in performance is normal, but I wanted to better understand the expected performance range for ox_core and ensure everything is running as intended in my development environment.
___________________________________________________________________________________________________________________________

## Environment
**ox_core version:** 0.31.2
**Operating System:** Win 11

___________________________________________________________________________________________________________________________

Thanks again for the great work, and I look forward to your response!

Best regards,
Primordial Studio

**Comment by thelindat** [comment]
Initial assumption is that it's occurring during a database query.

Most frameworks rely on an external resource (i.e. oxmysql) which will generally display that cpu spike instead.

I would need to see the profiler and know when these spikes are occurring, how many people are connected, and whatever other information seems relevant.

**Comment by Primordial-Devv** [comment]
After running some tests, I can confirm that the spikes occur specifically when SQL queries are being executed. Without the SQL queries, ox_core runs quite smoothly at around 0.04ms to 0.06ms on average.

In the profiler, the highest spikes I observed without SQL queries were around 0.06ms. The performance seems consistent otherwise.

Thanks again for your guidance, and please let me know if there's anything else I should check or further investigate.

____________________________________

Best regards,
Primordial Studio

**Comment by thelindat** [comment]
Try the nodejs update I linked and you'll probably have a a more consistent ms

**Comment by Primordial-Devv** [comment]
I’ve tested the artifact integrating Node.js 22 as you suggested, and I can confirm that it does indeed help reduce the runtime's overhead slightly. With this update, I now see an average performance of around 0.04ms, which is an improvement over the previous values.

Thanks again for the suggestion, and let me know if there’s anything else you think I should look into!

Best regards,
Primordial Studo
