### ISSUE TITLE
Incorrect text encoding

### ISSUE THREAD

**Issue by ESK0** [overextended/ox_core#176]
Hi,

our grade roles contains special characters and ox_core selects them incorrectly from DB. I tried to play with Connection options but without any luck:

Used characters as a group grade label: á, č, ď, é, ě, í, ň, ó, ř, š, ť, ú, ů, ý, ž

![{8D9D14F7-C467-438C-99A3-B8786323CCFE}](https://github.com/user-attachments/assets/1c409652-c11f-4b1e-9c32-f36dc8b7f73d)
Output: "�, č, ď, �, ě, �, ň, �, ř, š, ť, �, ů, �, ž"

Our database and table is correctly configured to use utf8mb4_unicode 
![{611E2A36-D8D9-415A-9F00-951173A4D976}](https://github.com/user-attachments/assets/0dcd6c05-0f5b-4618-ad07-85fa2cf1b05c)

When querying label manually everything is selected correctly
![{0774E85C-FBFD-464A-A684-0F63CC5B6F3C}](https://github.com/user-attachments/assets/75f8f28c-8280-4cc9-928f-e99046452988)

ox_core version: 0.31.1
PS: Back in the times of Lua ox_core we didn't have any issues. 

PS2: Apparently its only issue with group grades
![{FB00F0A0-E026-429B-B588-FB9879E87589}](https://github.com/user-attachments/assets/af14c19b-853b-44d7-9995-acb968111cf8)

**Comment by thelindat** [comment]
This seems to be a MariaDB bug that was fixed at some point (currently investigating). Since I select grades as a JSON value, the query is more like:

```sql
SELECT JSON_ARRAYAGG(ox_group_grades.label) AS grades FROM ox_group_grades WHERE `group` = 'czech'
```

![image](https://github.com/user-attachments/assets/c739514c-a807-45d2-8d17-b5a1e6937ef9)

MariaDB 11.4 is the current LTS and the problem is not present there.

**Comment by ESK0** [comment]
I was running MariaDB 11.1 and I can confirm updating to 11.4+ solved the issue.

**Comment by ESK0** [comment]
Hey there,

after few a days I noticed that the fix with updating the mariadb server only fixed the issue while querying with a external software. Initially I only checked this with a Datagrip
![{FDD59057-9656-4040-9608-464B6D5A6052}](https://github.com/user-attachments/assets/2f86fc59-34ee-491b-a3a6-3471e94c0168)

Unfortunately the server still got the text with incorrect encoding.
![{D3C590BE-A048-4B99-A697-358A4016BFFB}](https://github.com/user-attachments/assets/bad1ec1a-9480-4d60-afeb-b875de6a72a4)
![{3C83BCF3-1B6D-47A5-8DFE-8177DD54C3D3}](https://github.com/user-attachments/assets/4ef44c9a-8d5e-40e5-b0b1-a35747df4022)

Printing 'raw' grades before JSON parse
![{53F7AFAC-6EA2-402A-9B2E-120C345F6A27}](https://github.com/user-attachments/assets/7c75e06b-4d3a-415e-b98d-2b47af3da205)

Running latest ox_core version

**Comment by thelindat** [comment]
![{E16AC7F9-4CE8-430A-BF47-1D57320ED6FD}](https://github.com/user-attachments/assets/d07219f4-a71c-47ba-8b2b-d9f4ce81260d)

**Comment by ESK0** [comment]
> ![{E16AC7F9-4CE8-430A-BF47-1D57320ED6FD}](https://private-user-images.githubusercontent.com/65407488/374766387-d07219f4-a71c-47ba-8b2b-d9f4ce81260d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MzczMjUsIm5iZiI6MTcyODQzNzAyNSwicGF0aCI6Ii82NTQwNzQ4OC8zNzQ3NjYzODctZDA3MjE5ZjQtYTcxYy00N2JhLThiMmItZDlmNGNlODEyNjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDAxMjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkOWI3NGIwOGFkMGEwZTc1ZDYyN2VkNzg1N2RiMDkzOThkZjk3N2I3NWI2NDM0NTQxMWQ4MDM0MzMzNTQ5MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Y0iI9sZEBVPo84QwVfNV3BVeu1AuKMAYygoAt_DRLwA) ![{D6DA2D92-DFD5-46B6-8BA1-FC9502C55B09}](https://private-user-images.githubusercontent.com/65407488/374766746-c4e8dc0d-1d1c-40db-bbc9-e489cafede06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MzczMjUsIm5iZiI6MTcyODQzNzAyNSwicGF0aCI6Ii82NTQwNzQ4OC8zNzQ3NjY3NDYtYzRlOGRjMGQtMWQxYy00MGRiLWJiYzktZTQ4OWNhZmVkZTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDAxMjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMTMwYmRmMDY5MTY0ZmExYjBhN2UzMzM0OTQ2OGQyYWQ1N2I0MTBmODc3NGI1M2IwODcyMDc5OWZmNmE5MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zaVooqSgmWkAYWXpqYxenCp2aGYeUkgITqCjq_zkZyE)

I take it as a L... I uploaded the the new build to a different server folder

**Comment by ESK0** [comment]
Even after updating the core correctly (using the correct server directory -_-) The issue with encoding is still there... No issues in Datagrip but ox_core is fucked.. Are you using any options in a connection string? I tried setting charset: 'utf8mb4' but no luck there..

@antond15 Could you please try this at your machine tomorrow? I may look dumb but this is weird Af

**Comment by thelindat** [comment]
> Are you using any options in a connection string

Nothing outside of `user:password/database`.

**Comment by ESK0** [comment]
> > Are you using any options in a connection string
> 
> Nothing outside of `user:password/database`.

Today afternoon I tried a fresh db with a  ox_core recipe and it indeed works as expected...

**Comment by ESK0** [comment]
Hi,

after couple of days the issue came back and apparently there is an JOIN issue..
MariaDB version
![image](https://github.com/user-attachments/assets/8131ed35-42a9-4308-8fdc-65761366e855)

Basic JOIN:
![image](https://github.com/user-attachments/assets/65a77e88-c4eb-47f5-8cb4-5d85f316ae21)

LEFT JOIN:
![image](https://github.com/user-attachments/assets/a7fc0cec-3c83-4cef-80d8-97aee09c1969)

I honestly do not know why this happens but everything is configure correctly. Tables are using utf8mb4
![image](https://github.com/user-attachments/assets/ee6baf20-3401-4f36-a067-ab39d75ab389)

But apparently changing the JOIN for an optional JOIN... solved the issue for me.. I won't be creating a PR as this is just a one line change.

**Comment by thelindat** [comment]
My settings and mariadb version are the exact same as shown; nothing I do results in incorrect encoding since upgrading to 11.4.

You said it worked until it didn't, so what's to say LEFT JOIN won't meet the same outcome for you at some point. I really don't have a solution for you here.

**Comment by ESK0** [comment]
Definitely not a ox issue. I wrote it for a record if someone else find himself in same situation.
Its definitely another issue with JSON_ARRAYAGG as it happened out of nowhere after multiple hours/days of correct behaviour. I didnt meant to reopen the ticket.
