### ISSUE TITLE
OxStatuses - Max Value

### ISSUE THREAD

**Issue by Alexr03** [overextended/ox_core#207]
- Discussed here: https://discord.com/channels/813030955598086174/951683419769831465/1302503932316352582

I've been reading and searching throughout the discord for information about OxStatuses as I cannot find any documentation on it. By what I have been reading, the status is a "satisfied" level, rather than a "need" level like it is in ESX. This concept I understand and is fine.

However, there is currently no max value for a status, reaching 100+. In some cases such as hunger, we'd prefer is the max was 100 and ticks wouldn't go over that, similar to how the min value is 0.

Are there any plans to bring in a max value functionality?

**Comment by CeebDev** [comment]
Imo statuses are great as it is rn, minimum value is 0 and maximum 100. You can define default value when a new char is created and if it increase or decrease

**Comment by Alexr03** [comment]
Ahh I see, there is a max value.
I opened this because I looked back through the discord discussion and thought it was ticking over 100, but it wasn't it was ticking over 1.0 😅

Disregard this issue :)

**Comment by CeebDev** [comment]
https://github.com/overextended/ox_core/blob/0b832de051a20e94b8d4c89ae3394e1c7dfcf720/client/player/status.ts#L14
