### ISSUE TITLE
Get highest grade from group

### ISSUE THREAD

**Issue by PsychoShock** [overextended/ox_core#32]
Like the title said, it could be cool to add a option to get the highest grade from a specific group. This option will be useful to start making options for boss on jobs, gang, etc.

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/192164964-eb481130-0f3a-4f78-9369-521f934aafd6.png)
![image](https://user-images.githubusercontent.com/65407488/192164975-aa9374e3-ec77-4100-8619-4179c612a21f.png)
