### ISSUE TITLE
ox_core Modes

### ISSUE THREAD

**Issue by Eiskxlt** [overextended/ox_core#34]
I would love to have a feature for ox_core that you can change between modes like : 

standalone (ox-framework only),
ESX (Compatible with es_extended),
QB-Remastered (QB-OX) (Compatible with qb-core (from QB-Remastered)),
QB (Compatible with qb-core),
ND (Compatible with ND_core),

why ?

Because It would be perfect for Serverowners to have multiple options to combine Scripts for Better RP or Usage of other Scripts.

**Comment by thelindat** [comment]
Trying to shoehorn support for _other frameworks_ into a framework is silly. ESX and QB have very similar data structures and _even then_ it's still a nuisance to setup compatibility layers, which still won't work properly in most cases.

These are all competing frameworks, and adding support for them is silly and a complete waste of my time and effort.
