### ISSUE TITLE
[Bug] Phone Number

### ISSUE THREAD

**Issue by DogsGoBark** [overextended/ox_core#39]
Some people don't use `new phone who dis (npwd)`, and cannot create a character/load a character because the `phone_number` field cannot be null. Is it possible you can put the number generation in, if the `npwd` isn't loaded?

**Comment by GRZ-D3V** [comment]
This can be close since it was fix on https://github.com/overextended/ox_core/commit/749a5c4dd4707c09af54941eb3ec926846c330e4
