### ISSUE TITLE
SQL BUG

### ISSUE THREAD

**Issue by nutria22** [overextended/ox_core#41]
![image](https://user-images.githubusercontent.com/106103733/198831913-2e1d0d7e-6d6c-4f6f-bb82-b6b7c7e7d0ad.png)

[      script:oxmysql] Database server connection established!
[      script:oxmysql] SCRIPT ERROR in promise (unhandled rejection): Error: ox_core was unable to execute a query!
[      script:oxmysql] Unknown column 'stored' in 'where clause'
[      script:oxmysql] UPDATE vehicles SET stored = ? WHERE stored IS NULL ["impound"]
[      script:oxmysql] > <unknown> (@oxmysql/dist/build.js:22257)
[      script:oxmysql] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:oxmysql] > async rawQuery (@oxmysql/dist/build.js:22224)
[      script:oxmysql]

**Comment by thelindat** [comment]
"bug" Are you braindead?
