### ISSUE TITLE
player.set become nil when value set to false

### ISSUE THREAD

**Issue by skizmx** [overextended/ox_core#87]
Server
```
local data = {
    test1 = true,
    test2 = false,
    test3 = 'string'
}

CreateThread(function()
    local player = Ox.GetPlayers(true)[1]
    if player then
        for k, v in pairs(data) do
            player.set(k, v, true)
            print(player.get(k))
        end
    end
end)
```
Client
```
RegisterCommand('test', function(source, args, raw)
    print(player.test1, player.test2, player.test3)
end)
```
Server
![Screenshot 2023-08-09 223743](https://github.com/overextended/ox_core/assets/62847464/890e0e78-154f-40d8-922f-e96f2dc8b542)

Client
![Screenshot 2023-08-09 223502](https://github.com/overextended/ox_core/assets/62847464/d627174c-4d61-4b91-9586-ee962838373e)

**Comment by thelindat** [comment]
I see the issue but not much reason to fix it as I intend to move to statebags once filters get merged in 50 years from now.
