### ISSUE TITLE
Which version is currently stable? (click to spawn and black screen nothing happens)

### ISSUE THREAD

**Issue by Gellipapa** [overextended/ox_core#98]
Hi! I have tested several versions and none of them work. I have built everything, configured everything. I log into the server I make my character I click to spawn and black screen nothing happens. 

I looked at server console, no error I looked at client console no error.

I haven't started debugging yet, but it's a completely 0-started server so nothing should be interfering and as I write there is no error message. Simply the character does not spawn. 

Once again I write down that everything is built because the UIs appear and the console doesn't say anywhere that the build folder is missing.

Can you help me with what could be the problem? 

Thanks in advance for the answer :)

**Comment by Gellipapa** [comment]
UPDATE: 

I have debugged the spawn processor and there is something with fivem-apperance because it doesn't go into the callback so the promise doesn't get a value and waits forever. 

I tried calling fivem appearanceance with a command and it doesn't open anyway. 

On another server I copied the fivem-appearance one by one and it opens there. 

I deleted the cache so I don't know what the problem is why the UI doesn't open on the ox_core server.

**Comment by PsychoShock** [comment]
This core is still in WIP, if you don't know how to code I don't recommand you using this. But, latest version of core is "working".

**Comment by Gellipapa** [comment]
> This core is still in WIP, if you don't know how to code I don't recommand you using this. But, latest version of core is "working".

Hi! I know how to code it and I debugged it but the part I don't understand is why the fivem-appearance doesn't open even when copied to another server the fivem-appearance opens immediately.

This is unrelated to the spawn part since I tried it with command. 

Under OX_CORE the fivem-appearance does not appear. I looked at the NUI also the div is blank so even the react does not render out. 

This is quite an interesting problem.

**Comment by PsychoShock** [comment]
This is nothing related to `ox_core` since everything is working well. Make sure you have build everything correcly. This "issue" can be closed.

**Comment by Gellipapa** [comment]
> This is nothing related to `ox_core` since everything is working well. Make sure you have build everything correcly. This "issue" can be closed.

Hi! The reason why I didn't close it is that maybe someone else has the same error with ox_core that the fivem apperance is not displayed.

Yes, by default it is not an ox_core problem, but without it the ox_core does not work, so in this case it depends on it.

**Comment by Gellipapa** [comment]
I would appreciate it if someone other than me could download it and try to get it working properly. That's why it's not closed.

**Comment by LukeWasTakenn** [comment]
I only do development on my local ox_core server, it works without issues.

**Comment by Gellipapa** [comment]
> I only do development on my local ox_core server, it works without issues.

Hi! Thanks for the nice reply, it didn't work for me after several downloads and builds but it could be something wrong with my localhost server.
